name: first

on: push

jobs:
  
  job1:
    name: first_job
    runs-on: ubuntu-latest
    steps:
      - name: "step1"
        uses: actions/checkout@v2
      - name: "step2"
        run: "env | sort"

  job2:
    name: second_job
    needs: job1
    runs-on: windows-latest
    steps:
      - name: step1
        uses: actions/checkout@v2
      - name: step2
        run: "gci Env: | Sort-Object Name" 