name: first

on: 
  push:
    branches:
      - main
      - ch01-01
  pull_request:
    branches:
      - main

jobs:
  
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/Checkout@v3
      - name: Python Syntax Checker
        uses: cclauss/Find-Python-syntax-errors-action@master
    